fn main() {
    // Must run before tauri_build/codegen: `tauri::generate_context!` reads
    // the frontendDist directory at compile time and fails when it is
    // missing. The repository root's .gitignore ignores `dist/`, so the
    // placeholder page is intentionally NOT tracked — any fresh checkout
    // regenerates it here, and Task 4's real Vite build output naturally
    // supersedes it (this is a no-op whenever index.html already exists).
    ensure_frontend_placeholder();
    tauri_build::build();
}

fn ensure_frontend_placeholder() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set");
    let dist_dir = std::path::Path::new(&manifest_dir).join("../frontend/dist");
    let index = dist_dir.join("index.html");

    if !index.exists() {
        std::fs::create_dir_all(&dist_dir).unwrap_or_else(|e| {
            panic!(
                "cannot create frontend dist dir {}: {e}",
                dist_dir.display()
            )
        });
        std::fs::write(&index, PLACEHOLDER_HTML)
            .unwrap_or_else(|e| panic!("cannot write placeholder {}: {e}", index.display()));
        println!(
            "cargo:warning=generated placeholder frontendDist page at {} (real frontend lands with task 4)",
            index.display()
        );
    }

    // Watch the dist directory (not just the file) so deleting the
    // placeholder on a warm cache still reruns this script and regenerates
    // it before rustc re-expands generate_context!.
    println!("cargo:rerun-if-changed={}", dist_dir.display());
}

const PLACEHOLDER_HTML: &str = r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>AI Novel Desktop</title>
  </head>
  <body>
    <!--
      Placeholder frontendDist page, generated by build.rs when missing.
      Task 4 replaces desktop/frontend with the real Svelte app built into
      desktop/frontend/dist; until then this stub only exists so
      `cargo check` / `cargo test` can embed a valid context without a
      Node toolchain.
    -->
    <h1>AI Novel Desktop</h1>
    <p>Rust shell is running. The Svelte frontend lands in task 4.</p>
  </body>
</html>
"#;
